@startuml
left to right direction

class Director {
  construct()
}

interface Builder {
  buildPart()
}

class ConcreteBuilder {
  buildPart()
  getResult()
}

object Product

Director o-- Builder
Builder <|-right- ConcreteBuilder
ConcreteBuilder ..> Product

note bottom of Director
for all objects in structure {
  builder->BuildPart()
}
end note

@enduml