@startuml

class FlyweightFactory {
  getFlyweight(key)
}

interface Flyweight {
  operation(extrinsecState)
}

class ConcreteFlyweight {
  operation(extrinsecState)
  intrinsecState
}

class ConcreteUnsharedFlyweight {
  operation(extrinsecState)
  allState
}

class Client

FlyweightFactory o-right-> Flyweight: pool of flyweights
Flyweight <|.down. ConcreteFlyweight
Flyweight <|.down. ConcreteUnsharedFlyweight
Client -up-> FlyweightFactory
Client -up-> ConcreteFlyweight
Client -up-> ConcreteUnsharedFlyweight

@enduml